### ISSUE TITLE
API文档

### ISSUE THREAD

**Issue by tylerrrkd** [XuefengHuang/lianjia-scrawler#11]
你好，朋友！

不知道您是否方便提供下 **www.ershoufangdata.com** 的API文档。

谢谢你！

**Comment by MMMMercury** [comment]
你发错人了吧

---------------------------------------

**Comment by XuefengHuang** [comment]
谢谢对www.ershoufangdata.com感兴趣！目前爬虫开源，但是网站代码和API并未打算公开。

**Comment by tylerrrkd** [comment]
@XuefengHuang 好的 谢谢哥们。

**Comment by tylerrrkd** [comment]
@XuefengHuang 今天网站进不去哦。ping不到ip。

**Comment by tylerrrkd** [comment]
@XuefengHuang 看到备案说明了。啥时候能开呢。现在都不敢关电脑。。。
