### ISSUE TITLE
ERROR lack of lxml

### ISSUE THREAD

**Issue by walter211** [XuefengHuang/lianjia-scrawler#2]
报错
Couldn't find a tree builder with the features you requested: lxml. Do you need to install a parser library?

安装记录
(lianjia) xx-MBP:lianjia-scrawler$ pip install -r requirements.txt
Requirement already satisfied: appdirs==1.4.3 in ./lianjia/lib/python2.7/site-packages (from -r requirements.txt (line 1))
Requirement already satisfied: beautifulsoup4==4.5.3 in ./lianjia/lib/python2.7/site-packages (from -r requirements.txt (line 2))
Requirement already satisfied: bs4==0.0.1 in ./lianjia/lib/python2.7/site-packages (from -r requirements.txt (line 3))
Requirement already satisfied: lxml==3.7.3 in ./lianjia/lib/python2.7/site-packages (from -r requirements.txt (line 4))
Requirement already satisfied: MySQL-python==1.2.5 in ./lianjia/lib/python2.7/site-packages (from -r requirements.txt (line 5))
Requirement already satisfied: packaging==16.8 in ./lianjia/lib/python2.7/site-packages (from -r requirements.txt (line 6))
Requirement already satisfied: peewee==2.8.0 in ./lianjia/lib/python2.7/site-packages (from -r requirements.txt (line 7))
Requirement already satisfied: psycopg2==2.7.1 in ./lianjia/lib/python2.7/site-packages (from -r requirements.txt (line 8))
Requirement already satisfied: pyparsing==2.2.0 in ./lianjia/lib/python2.7/site-packages (from -r requirements.txt (line 9))
Requirement already satisfied: requests==2.13.0 in ./lianjia/lib/python2.7/site-packages (from -r requirements.txt (line 10))
Requirement already satisfied: six==1.10.0 in ./lianjia/lib/python2.7/site-packages (from -r requirements.txt (line 11))

**Comment by walter211** [comment]
换了内置的解析器
报了个新错：
list index out of range

**Comment by walter211** [comment]
搞定了，现在的问题是爬了半天数据库没进去

**Comment by XuefengHuang** [comment]
你用的是什么数据库啊？你可以在 config.ini里面选择数据库类型。你可以在数据库里看到五个表，首先爬cellinfo信息，然后根据cellinfo爬其他的信息。不知道你现在卡在哪里了？

**Comment by walter211** [comment]
@XuefengHuang 哥们能加个Q吗

**Comment by XuefengHuang** [comment]
@walter211 可以 363188552
