### ISSUE TITLE
跪求网址

### ISSUE THREAD

**Issue by MrLeion** [XuefengHuang/lianjia-scrawler#26]

**Comment by XuefengHuang** [comment]
私下邮箱已发

**Comment by MrLeion** [comment]
谢谢

**Comment by chile-zhong** [comment]
跪求网址  470707540@qq.com

**Comment by jeasonstudio** [comment]
@XuefengHuang 同求

**Comment by wi-x-wang** [comment]
求网址 yishengzhishui@gmail.com
谢谢🙏

**Comment by ShangguanQuail** [comment]
同求一份 liuye994@gmail.com
感谢

**Comment by Flowingsun007** [comment]
网址看了，很不错，不过能不能添加一个城市啊？想看【南京】的数据！！！

**Comment by Flowingsun007** [comment]
如果可以添加南京，那就十分感谢了！！！
P.S.网址：www.ershoufangdata.com

**Comment by godkillok** [comment]
@XuefengHuang 麻烦大佬给个网址，fujianhaowawa@163.com

**Comment by laychay** [comment]
同求大佬网址，980109510@qq.com

**Comment by XKINGSH** [comment]
大神可以增加广州房源数据吗？谢谢

**Comment by XuefengHuang** [comment]
统一回复网址：www.ershoufangdata.com

**Comment by CedricBailey** [comment]
同求 547513403@qq.com

**Comment by QtForQT** [comment]
为啥大家来这里问网址呢？图片上面有网址呀

**Comment by aprilweet** [comment]
> 统一回复网址：www.ershoufangdata.com

请问下网站声明数据来自于政府公开信息，所以想问下到底是来自链家还是政府呀？我觉得政府网签不如链家成交数据，更能反映市场行情。我知道这有点涉及法律风险，方便的话可以邮箱（[wm.april@gmail.com](url)）告知下哈，多谢。

**Comment by PyForMcj** [comment]
大佬能整个郑州的房源信息么
836965939@qq.com

**Comment by peterzhangbo** [comment]
跪求网站

**Comment by qiuzhaokun** [comment]
跪求网址
837787527@qq.com
