### ISSUE TITLE
能否做成全国房价数据库

### ISSUE THREAD

**Issue by royburns** [XuefengHuang/lianjia-scrawler#34]
把city放在数据库，我看文档，发现city是一个配置项，放在数据库里不是更好分类一些嘛

**Comment by royburns** [comment]
你自己的网站，是怎么处理多个城市的，每个城市一个数据库吗

**Comment by XuefengHuang** [comment]
每个city对应的区都不一样，我只是以一个为例。你可以根据自己的需求修改代码。我的网站是一个城市一张表。 @royburns

**Comment by royburns** [comment]
嗯嗯好建议,多谢

**Comment by zenkino** [comment]
@XuefengHuang 可以请教一下怎么获得城市所有的小区和对应的id吗？
比如我是想看上海这边的小区情况，可以怎么获取比较完整的list呢？

**Comment by XuefengHuang** [comment]
@zenkino [这个地方](https://bj.lianjia.com/xiaoqu/rs/)有所有小区的信息可以得到你要的。这个函数是实现方法 `core.GetCommunityByRegionlist(city, regionlist)`
