### ISSUE TITLE
关于数据的更新

### ISSUE THREAD

**Issue by zmuleyu** [XuefengHuang/lianjia-scrawler#36]
最近正在买房，大神的作品很好用，在此表示感谢！
不过，有点好奇的是，为什么历史交易价格的数据似乎十分滞后。

附上与另一个第三方机构数据的对比。
![1](https://user-images.githubusercontent.com/26676770/67115055-e4e2a280-f20f-11e9-9aae-513ada296a3b.png)

**Comment by XuefengHuang** [comment]
已更新 @zmuleyu 多谢关注

**Comment by zmuleyu** [comment]
更新真快，手动点赞！
还有两个小问题：
1、能否统一坐标轴的口径？见上图中的日期，这样有助于对比两套房同时期的价格；
2、在“小区详情板块”，不同小区内，不同户型，所用的颜色好像也不一样，能否统一下？

不要嫌我事多哈....毕竟实际买房就是有点麻烦.....

**Comment by zmuleyu** [comment]
这是另一个大神做的类似网站，https://jitaofang.com/
虽然技术比较简陋，但是很实用，必经他自己都买卖了几十套了......

**Comment by XuefengHuang** [comment]
@zmuleyu 

你的两个建议非常好。

1. 坐标轴没统一是由于数据我都是根据成交数据算得，每个小区成交情况不一样，所以起点终点都不一样。

2. 颜色不同是因为每个小区的户型都不一样，我怕漏掉所以展示了随机色。这确实是技术上偷懒导致的体验有点差。

我不是个前端，我有空看看怎么优化下吧。

你说的这个网站确实不错，有一些我没有的功能。比如推荐房源，每个房源的调价历史折线图。这些数据我这边都有，加上的话体验会好很多。

**Comment by zmuleyu** [comment]
嗯嗯，我是技术小白，完全不懂，只是从买房者的角度瞎提点想法~

他做的“历史房源信息”确实很好用，实际上包括做了两个方面的内容：一是同一房源的历史信息；二是同户型的历史价格。他也不是专做前端的，既然他能够实现，我猜想技术上应该不复杂。而且，之前有个插件，“刚需找房”，就是专注于这个功能：https://chrome.google.com/webstore/detail/%E5%88%9A%E9%9C%80%E6%89%BE%E6%88%BF/kdnhiabdomilddbmdjcpmcnnmdchccla

我个人觉得，如果你想做出特色，可以先集中精力解决问题一。如果你能统一不同小区坐标轴的口径，就可以进一步汇聚同一区域内，不同小区的历史价格曲线。举个例子，当我打算买两套相邻小区相同价位的房源时，通过判断各自的历史价格变动，就可以看出其未来的增长潜力，或是抗跌的能力。

当然，再次强调，我是小白，不知道说得有用没~
