### ISSUE TITLE
关于DEMO中的周边设施所使用的地图API

### ISSUE THREAD

**Issue by tylerrrkd** [XuefengHuang/lianjia-scrawler#8]
你好朋友！

谢谢你分享的程序。

可以问下DEMO中周边设施所使用的百度地图API是通过小区名定位还是通过经纬度获得的呢？
http://lbsyun.baidu.com/jsdemo.htm#i8_4

谢谢你。

**Comment by XuefengHuang** [comment]
通过经纬度获得的

**Comment by tylerrrkd** [comment]
@XuefengHuang 那经纬度数据在爬虫中没有找到。请教下是怎么获取的呢？
谢谢你！

**Comment by XuefengHuang** [comment]
百度提供API可以获得，我是直接调用它获取的。

**Comment by tylerrrkd** [comment]
@XuefengHuang Ohh.. 可能我表达得不对。。就是是通过小区名在百度地图上获得经纬度吗？
谢谢你！

**Comment by XuefengHuang** [comment]
对的

**Comment by tylerrrkd** [comment]
@XuefengHuang 好的！谢谢你！
